export const SET_ENABLED_MICRO = 'setEnabledMicro'
export const SET_ENABLED_VIDEO = 'setEnabledVideo'
export const SET_USER_STREAM = 'setUserStream'
export const SET_TOKEN = 'setToken'
export const SET_CURRENT_USER = 'setCurrentUser'
export const SET_LOADING = 'setLoading'
export const SET_ERROR = 'setError'
export const STOP_USER_STREAM = 'stopUserStream'
